logging:
  level:
    edu.asoldatov: "${LOG_LEVEL:INFO}"
    org.springframework: WARN
  file:
    name: target/log/application.log
datasource:
  db-online-store:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: "${DATASOURCE_URL}"
      username: "${DATASOURCE_USERNAME}"
      password: "${DATASOURCE_PASSWORD}"
      connection-timeout: 60000
      maximum-pool-size: 5
spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.xml
    drop-first: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "83b2dbb22f7c4566e33a"
            client-secret: "acfd5a92223af85cd1d08edc1c7d5a1634ccaf38"
            access-token-uri: "https://github.com/login/oauth/access_token"
            user-authorization-uri: "https://github.com/login/oauth/authorize"
            user-info-uri: "https://api.github.com/user"
            scope: "read:user,user:email"
          google:
            client-id: "159071480763-ivtj3f4u2a3anct10e68ubn46v17vkqs.apps.googleusercontent.com"
            client-secret: "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"
            scope: "email,profile"

server:
  port: 8080
frontend:
  host: "${FRONTEND_URL}"